### ISSUE TITLE
How would you handle scoping as C# does?

### ISSUE THREAD

**Issue by fsacer** [munificent/craftinginterpreters#104]
I'm stuck at reading Statements and State. I'm trying to get scoping rules the same as C# does so there would be diffrent rules inside function or outside like [this](https://ideone.com/zZO04K) but I'm unsure how would you check that based on enclosing environment. I'm probably going too far for this chapter. There is already [something](https://github.com/fsacer/FailLang/commit/65f93a4465866365a7ef1cf96ebee3fa3f88a5e1) I changed for unassigned variables.

**Comment by munificent** [comment]
This is a great question!

I don't think there's an easy way to implement C#'s "name can't refer to two different things in the same block" logic during the parse. Well, you could, now that I think about it...

For each block, keep a map of names to the variable the name resolved to. On each use of a variable, see if it's in the map. If not, add it and the reference to what the name refers to. If it is there, report an error if the current reference isn't to the same variable.

But I think it's probably a little cleaner to do it as a separate pass. You can write a visitor that walks the AST and figures out what declaration each name refers to. That would be a good time to report this error. We'll implement just such a visitor when we get to chapter 11 because we'll need to avoid inadvertently introducing dynamic scoping when we add closures.

**Comment by munificent** [comment]
I'll close this since I don't think there's any change I need to make to the book, but feel free to follow up on the issue if you want to discuss this more. :)
