### ISSUE TITLE
Parser: `term` and `factor` are a level off.

### ISSUE THREAD

**Issue by rkirsling** [munificent/craftinginterpreters#115]
The words `term` and `factor` are being misused in Lox's parser.

A polynomial is a summation of _terms_ which are each a product of _factors_.
These are correctly used in the [Wikipedia article](https://en.wikipedia.org/wiki/Recursive_descent_parser#Example_parser) on recursive descent parsing, but Lox is a level off.

I'm not certain what the best fix is—if you put them in the right place, `primary` would lose its spot and you'd need a new word for the operands of a `comparison`.

FWIW, the [V8 asm.js parser](https://github.com/v8/v8/blob/master/src/asmjs/asm-parser.h#L354) (_which, in doing away with precedence, looks strikingly similar to Lox's_) evidently calls these `AdditiveExpression` and `MultiplicativeExpression`.

-----

_P.S. Thanks a bunch for writing this book. It's super empowering to be able to jump into the repo of an arbitrary language / VM and find its lexer and parser "readable"._ :smile:

**Comment by munificent** [comment]
Ack, you're right! That took a while to fix. Had to redraw an illustration and everything.

> Thanks a bunch for writing this book. It's super empowering to be able to jump into the repo of an arbitrary language / VM and find its lexer and parser "readable".

You're welcome! That's exactly the goal. 😁

**Comment by mkrauskopf** [comment]
Is this fix going to be reflected in the books? The [Kindle version from Amazon](https://www.amazon.com/Crafting-Interpreters-Robert-Nystrom-ebook-dp-B09YLQSGKL/dp/B09YLQSGKL/) (I've bought) and the online version ([chapter 5](https://craftinginterpreters.com/parsing-expressions.html)) still contain the old Lox grammar with confusing `term` and `factor` usage.

Since the book is famous now ;), it spreads the incorrect grammar terminology among the readers (usually beginners I guess) who try to understand grammar and the parsing process. It would be great if the books can be updated with the new grammar.

Or is the "books update" tracked elsewhere?

Thanks for the approachable, superb book. 🚀

**Comment by munificent** [comment]
Oops, looks like I just missed those table headers when I fixed it everywhere else.

Since I published the print edition, I haven't been making any more updates to it. I probably will at some point, but it's quite a hassle to keep track of the changes, fix the typesetting, etc. So, for now at least, I've just been leaving issues open in the repo to tracker changes that should be done at some point.

**Comment by HuM4NoiD** [comment]
I am following the html version of the tutorial [here](https://craftinginterpreters.com/parsing-expressions.html#ambiguity-and-the-parsing-game), it still has the rules:
```
term           → factor ( ( "-" | "+" ) factor )* ;
factor         → unary ( ( "/" | "*" ) unary )* ;
```
I looked at the [code](https://github.com/munificent/craftinginterpreters/blob/01e6f5b8f3e5dfa65674c2f9cf4700d73ab41cf8/java/com/craftinginterpreters/lox/Parser.java#L372) and it is following the same rules.

I have started following the series, Do you recommend sticking with the series or proceed with the actual definition?
I'll try being braver and change the production rules a little bit.


Again, thanks for breaking down the entry barrier for building languages.
