### ISSUE TITLE
Reference & value semantics

### ISSUE THREAD

**Issue by bisthebis** [munificent/craftinginterpreters#12]
In chapter 3, when you introduce classes, you explain that we can pass objects to functions.
Wouldn't be worth it to talk about value semantics and reference semantics ? What happens if I pass an object to a function and that function calls a method that mutates the object ?

Maybe I'm *a bit obssessed* by these semantics (might be because of my C++ background) but it seems important to clarify this. At least, deciding what semantics are used by default, at best, using a paragraph to describe it

**Comment by munificent** [comment]
Ah, yes. This is one of those things I take for granted because I'm used to managed languages where passing by reference is just The Way. We absolutely will cover this in egregious detail in later chapters since we literally have to implement what it means to pass a parameter ourselves.

Chapter 3 is already pretty long so I'll probably defer it to those chapters if that sounds reasonable.
