### ISSUE TITLE
Statements and State

### ISSUE THREAD

**Issue by colms** [munificent/craftinginterpreters#122]
Some stuff that might be worth throwing an eye over:
- rules blocks in this chapter have semicolons after each rule but earlier chapters don't e.g. program     = statement* EOF ; (that semicolon there)
- "There are no places in the grammar where both an expression and a statement is allowed." 
Am I right in saying "places" (plural) is being matched with "is"? Maybe: "There is no place" or "There is nowhere". or changing the "is" to "are" 
- " A `print` token" => "A `PRINT` token". I'm not sure on the style guide on whether token that appear in text should remain capitalized.
- "Some parsers writers" => "Some parser writers" or "Some parser's writers".
- "in microcosm" => "in a microcosm"
- "beverage" is in quotes. I just want to be sure they shouldn't be backticks are anything else. There later `beverage` is in backticks but the context is different so I'm not sure.
- "and returns it." Colon instead of period because code black follows?
- "Like most statements it starts with a leading keyword." - I'd have a comma in there.
- In the block after "we add a new statement tree for a variable declaration", should the Print line also be highlighted? It probably should but I just want to be sure.
- "In the primary()," => "In primary()," or "In the primary() method/function" whichever it is. I'm basing this on the fact that you explicitly follow with the word "method" elsewhere e.g. "expression() method".
- isEven()‘s - this is a nitpick but the direction of that apostrophe seems off.
- "limited computers" => "limited power of computers". (nitpick)
- assignment  = identifier "=" assignment
  - just to be sure, this means Lox can do:
```
var x = 0;
var y = 0;
```
but not:

```
var x, y = 0;
```
or
```
var x = y = 0;
```
right?
- "L-value" => "An l-value" just for symmetry because the "r-value" is lowercase. It also kind of looks like a different term.
- sometimes you use "lvalue" and "rvalue" with hyphens and sometimes without.
- "If we find a `=`" => "If we find an `=`" because pronounced `=` starts with a vowel.
- "or the less common static scope" => "less commonly known as static scope". I think that's what you mean?
- "curly-braced blocks." - period to colon before code block.
- "block scope" is introduced only in a side note but used in main text thereafter.
- The "check this out" code block:
  - "increments and prints count" => "increments and prints global count"
  - the `increment()` function is never used in code nor referred to in text.
  - I don't like the use of a for loop in the sumToTen function. It seems needlessly complex and was only previously mentioned in the "Lox Language" chapter. I'd leave mention of for for the control flow chapter and think it's overkill to express what you're referring to here (score of variables).

**Comment by munificent** [comment]
> " A print token" => "A PRINT token". I'm not sure on the style guide on whether token that appear in text should remain capitalized.

I think it's a little clearer to use the literal text of the token (`print`) instead of the enum that corresponds to it, so sticking with that.

> "in microcosm" => "in a microcosm"

This reads a little funny, but it's deliberate. I'm using "microcosm" as an... adverb? not a noun. In the same vein as "in reverse" or "in miniature".

> In the block after "we add a new statement tree for a variable declaration", should the Print line also be highlighted? It probably should but I just want to be sure.

It should, yes, though this trips up a lot of readers. If you notice the slugline on the right, it says "replace one line". In the previous version of the code there, there was no comma at the end of the print line, so it's telling you to add that now.

> isEven()‘s - this is a nitpick but the direction of that apostrophe seems off.

You are correct! I put a surprising amount of effort into automating getting the punctuation right, but the script that handles it gets tripped up on apostrophes following inline code. :-/

> just to be sure, this means Lox can do:
> var x = 0;
> var y = 0;

Yes.

> but not:
> 
> var x, y = 0;

Right.

> var x = y = 0;
> right?

You can do this. It's initializing `x` with the result of the assignment expression `y = 0`.

> "or the less common static scope" => "less commonly known as static scope". I think that's what you mean?

I think the quotes technically make the use-mention distinction technically unambiguous, but you're right it's unclear. Fixed.

> I don't like the use of a for loop in the sumToTen function.

Yeah. I think using *functions* is the even more confusing part here since functions directly muck with scope themselves. Used a different example.

Did all the other things you suggested. As always, thank you!
