### ISSUE TITLE
Interpreter.globals are being referenced before being explained

### ISSUE THREAD

**Issue by initram** [munificent/craftinginterpreters#132]
I know that you normally show the caller before the callee in you code examples, but in this example there is quite a distance to the part where you introduce the global environment.

It is first used in 10.2.1: http://www.craftinginterpreters.com/functions.html#telling-time
Then it is shown implmented in 10.4.1: http://www.craftinginterpreters.com/functions.html#interpreting-function-declarations

This felt strange to me reading it, as my compiler was in a "broken" state for too long for my comfort. I feel that the small code snippet from the later section could be moved up.

**Comment by munificent** [comment]
Oh, shoot, you're exactly right. I try to order things in the chapter such that I don't leave the reader hanging too long. This chapter was more difficult than most to find a natural order for things since you need functions before you can call them and you need calls before you can do anything useful with declarations. Then the one native function is even harder to weave in naturally. I missed the dependency on `globals`.

I'll try to re-arrange some stuff to make this flow better. Thanks for pointing this out!

**Comment by alexito4** [comment]
It just happened to me 😂 tbh even just a mention that it will be explained later would suffice. Just something so we don't scratch our heads thinking we missed an important step ^^
