### ISSUE TITLE
Deduplicate finding a resolved variable

### ISSUE THREAD

**Issue by henke37** [munificent/craftinginterpreters#147]
As per chapter 11 (Resolving and Binding) there are two methods which seem to share common code.

```java
  Object getAt(int distance, String name) {
    Environment environment = this;
    for (int i = 0; i < distance; i++) {
      environment = environment.enclosing;
    }

    return environment.values.get(name); 
  }
```

```java
  void assignAt(int distance, Token name, Object value) {
    Environment environment = this;
    for (int i = 0; i < distance; i++) {
      environment = environment.enclosing;
    }

    environment.values.put(name.lexeme, value);
  }
```

Likewise their callers are very similiar:

```java
  private Object lookUpVariable(Token name, Expr expr) {
    Integer distance = locals.get(expr);
    if (distance != null) {
      return environment.getAt(distance, name.lexeme);
    } else {
      return globals.get(name);
    }
  }
```

```java
    Integer distance = locals.get(expr);
    if (distance != null) {
      environment.assignAt(distance, expr.name, value);
    } else {
      globals.assign(expr.name, value);
    }
```

I suggest moving the calls that differ out of the code and merging the resulting identical code. The end result is that the code for looking up the variable and its scope is DRY (Don't Repeat Yourself) and only the code that actually changes is duplicated, avoiding WET (Write Everything Twice).

**Comment by rkirsling** [comment]
I found that this can all be greatly simplified by doing two things:

1. Instead of introducing `getAt`/`assignAt`, introduce an `ancestor(n)` method to `Environment` and  have `define`/`get`/`assign` only interact with the current environment.

2. Instead of introducing a `globals` field in `Interpreter`, set depth for globals to `scopes.size()` in `Resolver::resolveLocal`.

As a result,
```java
    if (distance != null) {
      environment.assignAt(distance, expr.name, value);
    } else {
      globals.assign(expr.name, value);
    }
```
...turns into...
```java
    environment.ancestor(distance).assign(expr.name, value);
```

**Comment by munificent** [comment]
That does look nice! I'm almost done with the next chapter, but when I get a chance, I'll circle back and see if I can work this in.

**Comment by munificent** [comment]
> Instead of introducing a globals field in Interpreter, set depth for globals to `scopes.size()`

I initially thought that wouldn't work because you don't know how long the environment chain is because you don't know how deep the call chain is until runtime. But the environment chain doesn't contain the *call* stack, just the chain of enclosing lexical scopes. `executeBlock()` in Interpreter stuffs the series of environments for each pending call on the *Java* stack.

So, yes, this work! It's a great idea.

...Except for one minor thing. The semantics of global variables are a little different. For a local variable, we know a read will succeed at runtime if the resolver resolved it. For globals, because we allow implicit forward declarations, we have to check at runtime to see if the variable is defined when its read. `Environment#get()` does that, but `Environment#getAt()` does not.

We could fix that by having Environment check to see if it's the global one (look for a `null` parent). If so, on a variable get, it would check to see if it's actually present. But that starts to look like a larger code change which would force me to rework a lot of text.

I don't think it's a significant enough improvement to throw out that work. I am trying to get the book done before the sun goes nova... :)

`ancestor()` was a great idea. That's in now. Thank you!

**Comment by rkirsling** [comment]
Yeah, that was the "subtractive" part I was concerned about. 😅 It suffices to remove the `if (enclosing != null)` branches in `get`/`assign`, but then you'd be directly undoing the work of 8.5.1. (_As for the needless existence checks in local scopes, I guess I decided I was okay with that part._)

Thanks for considering my ideas regardless!
