### ISSUE TITLE
Inheritance: Two concerns.

### ISSUE THREAD

**Issue by rkirsling** [munificent/craftinginterpreters#193]
How exciting to have a full-fledged tree-walk interpreter! 🎊 
Thanks as always for the wonderful book and for letting us all help make it better.

I noticed a couple of minor issues while going through Chapter 13:

1. The `Superclass must be a class.` error in [`Interpreter::visitClassStmt`](https://github.com/munificent/craftinginterpreters/blob/master/java/com/craftinginterpreters/lox/Interpreter.java#L118) is being reported at the class identifier and not the superclass identifier. I can submit a PR to fix this.

2. In reading this paragraph from 13.3.2...

    > We _could_ add a field to LoxFunction to store a reference to the LoxClass that owns that method. The interpreter would keep a reference to the currently-executing LoxFunction so that we could look it up later when we hit a super expression. From there, we’d get the LoxClass of the method, then its superclass.
    
    ...I can't help but feel that the second sentence doesn't follow from the first. If a  `LoxFunction` knows the `LoxClass` to which it belongs, then we can simply define `super` along with `this` in [`LoxFunction::bind`](https://github.com/munificent/craftinginterpreters/blob/master/java/com/craftinginterpreters/lox/LoxFunction.java#L32). This also means the superfluous `super` scope and the magic [`- 1`](https://github.com/munificent/craftinginterpreters/blob/master/java/com/craftinginterpreters/lox/Interpreter.java#L412) go away. The interpreter needs not carry any extra state.

    You might still view "That’s a lot of plumbing." as the conclusion, but I think this paragraph could be made less of a strawman. :smile:

**Comment by munificent** [comment]
> I can submit a PR to fix this.

Yes, thank you!

> ...I can't help but feel that the second sentence doesn't follow from the first. If a LoxFunction knows the LoxClass to which it belongs, then we can simply define super along with this in LoxFunction::bind. This also means the superfluous super scope and the magic - 1 go away. The interpreter needs not carry any extra state.

Ah, interesting! You're right, this would work. But deferring it to `bind()` feels unnecessary to me. `bind()` is called every single time a method is about to be invoked. But, for any given method, `super` will always resolve to the exact same class, regardless of what object the method is invoked on.

Binding `super` in a scope at class definition time does that work once so that you don't have to do it on each invocation. It's essentially turning a class definition like:

```
class Base {
  foo() {
    print "Base.foo()";
  }
}

class Derived < Base {
  foo() {
    print "Derived.foo"();
    super.foo();
  }
}
```

into roughly:

```
class Base {
  foo() {
    print "Base.foo()";
  }
}

{
  var super = Base;
  class Derived < Base {
    foo() {
      print "Derived.foo"();
      super.foo();
    }
  }
}
```

And then, after the class definition is done, we no longer have to think about `super` at all. The methods just close over it.
