### ISSUE TITLE
Please add a Recommended Reading or Further reading section at the end of the book

### ISSUE THREAD

**Issue by ghost** [munificent/craftinginterpreters#221]
... which has links to resources about learning other stuff like static typing, type inference etc.

**Comment by munificent** [comment]
No promises, but a bibliography or recommended reading is a good idea. :)

**Comment by jyn514** [comment]
I've been reading the [Dragon Book](https://en.wikipedia.org/wiki/Compilers:_Principles,_Techniques,_and_Tools) as I go along and the combination of theory from that and practice from this book have been really helpful.

**Comment by egordorichev** [comment]
@ghost I'd just suggest taking the Java AST part and making a more optimized version of it, then figuring out how to do checks on it, it's much more simple than it sounds. After that you might be interested in making the VM register based rather than stack based, that's also a pretty straight forward process once you wrap your head around registers. And yet another cool thing might be figuring a better structure for the language overall, maybe splitting it into compiler and VM to allow easier bytecode saving/loading. I had a ton of fun with my own language, and I still will, and I wish you too :)

**Comment by munificent** [comment]
After a lot of thought, I've decided *not* to do this. I really need to get the book done and that means *not* adding more stuff to it. It's large enough to kill a small mammal as it is. :)
