### ISSUE TITLE
if does not require parenthesis

### ISSUE THREAD

**Issue by sschellhoff** [munificent/craftinginterpreters#226]
You write in your book that if requires the closing parenthesis after it's condition for the parser to correctly parse. That is not right. I build some parsers in the past the doesn't needed it and even your parser doesn't.
```
Check this code:
  private Stmt ifStatement() {
    //consume(LEFT_PAREN, "Expect '(' after 'if'.");
    Expr condition = expression();
    //consume(RIGHT_PAREN, "Expect ')' after condition.");

    Stmt thenBranch = statement();
    Stmt elseBranch = null;
    if(match(ELSE)) {
      elseBranch = statement();
    }

    return new Stmt.If(condition, thenBranch, elseBranch);
  }
```
I just commented those lines which consume the parenthesis out and the parser still works. But now it wants if statements to not have enclosing parenthesis around their condition. Even greater, they are automatically optional because a condition is just an expression and expressions can have parenthesis around them.
Maybe it is my fault and i forgot a case in lox where this doesn't work.
The part of your text where you mention it is:

> The parentheses around the condition are only half useful. You need some kind of delimiter between the condition and the then statement, otherwise the parser can’t tell when it has reached the end of the condition expression.
at chapter control-flow > [conditional-execution](http://craftinginterpreters.com/control-flow.html#conditional-execution), third side-note.

**Comment by munificent** [comment]
There are some cases that are ambiguous if you don't have an explicit delimiter between the if condition and the then statement. Consider:

```
if a - b(c);
```

This could be parsed as either:

```
if (a) -b(c);
if (a - b) (c);
```

There are a couple of other similar ambiguities. Basically, when you butt an expression right next to a statement, both of those grammars have enough options (especially because of ExpressionStatement), that it's unclear where the expression ends and the statement begins.
