### ISSUE TITLE
Some typos in part 2

### ISSUE THREAD

**Issue by beoboo** [munificent/craftinginterpreters#259]
**§3.4.3** 
`!false; // true;` should be  `!false; // true.`

**§3.5**
```
{
  print "One statement";
  print "Two statements.";
}
```

should be
```
{
  print "One statement.";
  print "Two statements.";
}
```

(or both without the dot)

**§5.2.2**
In the `defineAST` method there is `writer.println("")` instead of `writer.println()`.

**§5.3.3**
In the `defineAST` method there is another `writer.println("")` instead of `writer.println()` (after `The base accept method.`).

**§6.2.1**
The method `check` should be written as 

```
private boolean check(TokenType type) {
  if (isAtEnd()) return false;
  return peek().type == type;
}
```

instead of 

```
private boolean check(TokenType tokenType) {
  if (isAtEnd()) return false;
  return peek().type == tokenType;
}
```

**§9.4**
In the new grammare rule, only "While" should be highlighted, not "Var".
`"Expect ')' after condition."` should be `"Expect ')' after while condition."`

**§10.1.4**
`if (arguments.size() != function.arity()) {` starts one space too early.

**§11.3.1**
I think that `Lexical scopes nest and in both the interpreter and the resolver, they are treated like a stack. ` should be instead `Lexical scopes nest in both the interpreter and the resolver, and they are treated like a stack.`

Also
```
private void beginScope() {
    scopes.push(new HashMap<String, Boolean>());
}
```

should be 
```
private void beginScope() {
    scopes.push(new HashMap<>());
}
```

There is an inconsistency between `declare` and `define`methods (the former is not inlined, the latter is):
```
private void declare(Token name) {
    ...
    Map<String, Boolean> scope = scopes.peek();
    scope.put(name.lexeme, false);
}
```

while 
```
private void define(Token name) {
    ...
    scopes.peek().put(name.lexeme, true);
}
```

There is an inconsistency between other methods and 
```
public Void visitReturnStmt(Stmt.Return stmt) {
    if (stmt.value != null) {
      resolve(stmt.value);
    }

    return null;
}
```

Here ^ the then branch is under a block and not inlined.
```

**Comment by munificent** [comment]
Oh wow, thanks for all these! I fixed them all except:

> In the new grammare rule, only "While" should be highlighted, not "Var".
"Expect ')' after condition." should be "Expect ')' after while condition."

That's because you need to change the previous line to add a comma at the end. This trips up a lot of people. At some point, I might try to tweak the build script to show these lines specially.

> should be
>
> ```java
> private void beginScope() {
>     scopes.push(new HashMap<>());
> }
> ```

That's actually a Java 8 feature. Java 7 adds the diamond operator, but Java 8 extends it to allowing method parameters to provide the context. I try to stick to Java 7 to the book (mainly to forestall questions around whether or not I should be taking advantage of lambdas.)

> There is an inconsistency between declare and definemethods (the former is not inlined, the latter is):

That's because later we add some code inside `declare()` that uses that variable.

> Here ^ the then branch is under a block and not inlined.

Same.

Thank you! 😁
