### ISSUE TITLE
Implementing Challenge 6.1 (comma operator) adds a hidden surprise Challenge to Chapter 10: Functions

### ISSUE THREAD

**Issue by woolsweater** [munificent/craftinginterpreters#263]
The first challenge in Chapter 6 is to implement a comma operator. The comma is, of course, also used to separate arguments in a function call.

According to the code in Chapter 10, when parsing the argument list, we make a simple call to `expression()`, with the assumption that it will stop at the next comma `Token`. But if one has kept the code for the comma operator*, `expression()` merrily consumes the entire argument list, treating it as a single expression. That results in a runtime error for mismatched arity.

<p>
<details> 
  <summary>I'm not 100% certain about my solution, but I took inspiration from the <a href="">solution for confining the <code>break</code> statement to loops</a>. </summary>
  <p>
    I added a) a flag for whether we are currently parsing an argument list, and b) a counter for parenthetical groups (so that we continue to handle comma operators inside <em>nested</em> parens correctly, e.g. <code>sayHi(("dear", "esteemed"), "reader")</code> prints <code>"Hi, esteemed reader!"</code>). Then the parser method for the comma operator returns early if <code>isArgumentList</code> is true and there is no current paren grouping.
  </p>  
</details>
</p>

Straightforward enough to resolve, and a fun bonus challenge, but I'd suggest a footnote or other warning about it be added to Chapter 10.

---

*Maybe I just wasn't supposed to keep it?

[0]:https://github.com/munificent/craftinginterpreters/issues/119

**Comment by munificent** [comment]
Ah, great point! Simply changing `expression()` to include comma does have the problem you describe. The fix is pretty simple. I updated my answer note to mention it. The relevant part is:

Keep in mind that commas are already used in the grammar to separate
arguments in function calls. With the above change, this:

```lox
foo(1, 2)
```

Now gets parsed as:

```lox
foo((1, 2))
```

In other words, pass a single argument to `foo`, the result of evaluating
`1, 2`. That's not what we want. To fix that, we simply change the way we
parse function arguments to require a higher precedence expression than the
comma operator:

```java
if (!check(RIGHT_PAREN)) {
  do {
    if (arguments.size() >= 8) {
      error(peek(), "Cannot have more than 8 arguments.");
    }
    arguments.add(equality()); // <-- was expression().
  } while (match(COMMA));
}
```

**Comment by woolsweater** [comment]
Ah ha, using precedence to control it. Excellent, thanks!
