### ISSUE TITLE
Question about Chapter 14 - Line counting and challenge 1

### ISSUE THREAD

**Issue by beoboo** [munificent/craftinginterpreters#284]
We're going to define a RLE for the line counting. 

In the side note you say "Since line information is only used when a runtime error occurs, we don’t want it next to the bytecode, taking up precious space in the CPU cache and causing more cache misses as the interpreter skips past it to get to the real instructions it cares about." 

But we're adding at least a pointer, or even one pointer and two ints in the challenge solution.

Why is that better than including the simple `int line;` into each chunk? 

Is this because we want to link line counting between chunks? 

If yes, wouldn't this be clearer if instead chunks were linked one another?

**Comment by dasdware** [comment]
I think, when executing the VM, not the whole `Chunk` struct is loaded into the cache, but only the data directly used. In this case that is the `code` portion of the chunk. As long as you don't need the line information, the CPU will never look at it, since it is a whole separate blob of memory. Therefore, it doesn't matter how the line information is stored.

IMHO, "next to the bytecode" is a bit misleading. I think, what the author really means is "interleaved with the bytecode". For example, if you had a bytecode format like `[LINE][OP_CODE][PARAMETERS]...`, then the line information would be loaded into the cache, but not be of any use as long as no error occurs.

**Comment by munificent** [comment]
> I think, what the author really means is "interleaved with the bytecode".

That's correct. The previous paragraph says:

> separate array instead of interleaving it in the bytecode itself

Reworded the aside to make this clearer. :)
