### ISSUE TITLE
Typos and questions about Part III

### ISSUE THREAD

**Issue by beoboo** [munificent/craftinginterpreters#289]
*§16.2*
The TokenType enum lists keywords ordered alphabetically, except for FUN and FOR :)

*§17*
In the challenges, there is a final "3 TODO"... what's that about?

*§18.4.2* 
`That covers all of the operators that return Boolean results except the logical operators _&&_ and _||_.` should be `That covers all of the operators that return Boolean results except the logical operators _and_ and _or_.`

*§19.4*
In the `valuesEqual` function, are we just assuming that the VAL_OBJ is a string?

*§19.4.1* 
It would be a nice challenge (I think for a future chapter about functions) to add support for a string function like `join`.

Also, why do we have `takeString`? Couldn't we just call `allocateString`? (I know there could be missing pieces here, but maybe not...)

Finally, you say "But, for concatenation, we’ve already dynamically allocated a character array on the heap. Making another copy of that would be redundant (and would mean concatenate() has to remember to free its copy). Instead, this function claims ownership of the string you give it." Ehm... why do we do that then?

*§19.5*
Typo: `chrews` instead of `chews`.

**Comment by munificent** [comment]
Thanks, these are great!

> In the `valuesEqual` function, are we just assuming that the VAL_OBJ is a string?

For now, yes. When we add other object types in a later chapter, that code gets replaced.

> It would be a nice challenge (I think for a future chapter about functions) to add support for a string function like `join`.

That's a good idea. You couldn't write that entirely in Lox since there's not enough low level string functionality exposed to do it. But you could add it as a native function.

> Also, why do we have takeString? Couldn't we just call allocateString? (I know there could be missing pieces here, but maybe not...)

You could, but that will miss a step (interning the string) that we add in a later chapter.

>  Instead, this function claims ownership of the string you give it." Ehm... why do we do that then?

`concatenate()` needs to dynamically allocate because it's the only function that knows how long the resulting string will be. But after it does that, it doesn't need to own it, so we can immediately claim the string and give ownership to the ObjString.

Fixed the other things you mentioned. :)
