### ISSUE TITLE
Marginal Collisions in the Typesetting

### ISSUE THREAD

**Issue by pqnelson** [munificent/craftinginterpreters#292]
In some layouts, the "margin grafiti" (as Knuth would call it) and the source file annotations overlap.

See the attached screenshot, where `main.c\n add to top of file` overlaps with "The code tests for one and two arguments, ..." in the margins on the right-hand-side.

![layout-nightmare](https://user-images.githubusercontent.com/1752731/46622524-d1bad400-cadf-11e8-86b2-b637eedead87.png)

**Comment by rkirsling** [comment]
Might be a bug in FF for Linux? This doesn't seem to repro in latest FF/Chrome/Safari/Edge on Mac/Win.

**Comment by pqnelson** [comment]
Right, I forgot, I probably should add version info (sorry about that!). I saw this on Firefox 62.0.3 (64-bit) on Ubuntu 16.04.5 Xenial. Let me try upgrading FF and see what happens...

Chrome version 69.0.3497.100 (Official Build) (64-bit) **does not** have this bug on the same box (on the same page).

**Comment by pqnelson** [comment]
I still get this problem for Firefox 63.0b12 (64-bit) on Ubuntu, let me try it out on Windows later today when I get home.

**Comment by pqnelson** [comment]
So, on Windows, there is **no such bug** on Chrome or Firefox. (Now that I'm writing, I realize I forgot to test IE...or whatever MS replaced it with...I can do that too, if you'd like.)

**Comment by rkirsling** [comment]
Nice, looks like you found a legitimate bug in FF for Linux!
You should report it at https://bugzilla.mozilla.org/. :smile:

**Comment by munificent** [comment]
That's pretty strange. I can't repro it with Firefox 64.0 on my Mac. Do you see any errors in the JS console? Does a force-refresh help?

**Comment by billti** [comment]
I was using the new Microsoft browser and seeing it, which is based off Chromium. Using Chrome Canary (Version 78.0.3874.3 (Official Build) canary (64-bit)) I also see it. (I'm on Windows 10). 

See below example, but it happens quite a lot.

![margins](https://user-images.githubusercontent.com/993909/62497891-2a0b4280-b792-11e9-86ec-964a6c1064b9.png)

**Comment by billti** [comment]
FYI: Seems to be the 'top' property in the asides getting set incorrectly. I can't step into the minified jQuery to see why it's not working when called from `script.js`, but looks like the call to `.position()` is returning different values in Chrome Canary and Chrome. See below with Chrome release on the left and Canary on the right. Both screen clipping taken on the same `aside` in the same page, with the same browser size (full screen). 

Note how in Canary `top` on the returned `pos` value is less (and `left` is 0 too - but that doesn't affect layout here).

![image](https://user-images.githubusercontent.com/993909/62498940-c5ea7d80-b795-11e9-9707-754380c84fdf.png)

**Comment by billti** [comment]
Last post on this (sorry for the spam and screen shots).

I downloaded the content and played around locally, and it looks like the empty span used to position the aside is the cause.

On Chrome release, you can see it is in the middle of the code, as expected.

![empty-span-chrome](https://user-images.githubusercontent.com/993909/62500189-41e6c480-b79a-11e9-8dd9-c44d38e9d15c.png)

However on Chrome Canary, you can see it is at the top of the parent code block, even though the element ordering would make it seem like this is wrong.

![empty-span-canary](https://user-images.githubusercontent.com/993909/62500234-5e82fc80-b79a-11e9-8d16-0a4da039e4c0.png)

If I put some simple content in the span (even a space, but here an `x`) it gets positioned correctly again.

![image](https://user-images.githubusercontent.com/993909/62500348-d3eecd00-b79a-11e9-8d76-fe1575d7e2be.png)

I'm not a spec wonk on CSS, but from reading this Stack Overflow answer <https://stackoverflow.com/questions/10778949/why-does-adding-text-to-a-span-change-its-position> , perhaps this is the correct behavior for an empty span, and thus maybe a bug fixed in recent browsers, and the fix is to use a span with content for positioning.

**Comment by munificent** [comment]
I think this is fixed by d509591f43c37aa53e3a34bf0abff98043262788. If not, let me know and I'll reopen.
