### ISSUE TITLE
Typos in Chapter 16

### ISSUE THREAD

**Issue by aidtopia** [munificent/craftinginterpreters#338]
I believe you _might_ have changed a word in the Vonnegut quote at beginning of Chapter 16:

> Literature is idiosyncratic arrangements in horizontal lines **in** [should be _of_?] only twenty-six symbols, ten arabic numbers, and about eight punctuation marks.

Most other search hits have _of_.  Some also capitalize _Arabic_.

> This isn’t really a book on good C programming practice, but I hate to encourage bad style, so **lets** [should be _let's_, with an apostrophe] go ahead and handle the errors.

**Comment by munificent** [comment]
I think [this](https://books.google.com/books?id=AXFUX-IuuUgC&pg=PA16&lpg=PA16&dq=%22Literature+is+idiosyncratic+arrangements%22&source=bl&ots=0REzijfoZ5&sig=ACfU3U0LAXmGko35lC-NswzQ9jR62zYX0g&hl=en&sa=X&ved=2ahUKEwiXzdH4xo7gAhXBj1QKHQ_hAC0Q6AEwAnoECAcQAQ#v=onepage&q=%22Literature%20is%20idiosyncratic%20arrangements%22&f=false) is the original source of the book. It uses "in" and doesn't capitalize "arabic". It does add "phonetic", which was missing from the source I got the quote from, so I fixed that. I also capitalized "Arabic", because I think that's correct.

You're totally right on the other one. Thanks!
