### ISSUE TITLE
Compare hash in tableFindString

### ISSUE THREAD

**Issue by ksceriath** [munificent/craftinginterpreters#347]
Shouldn't we also compare the hash of the strings first, before memcmp? Wouldn't that speed up the interning logic?

**Comment by ksceriath** [comment]
Also, wouldn't it be better if tableFindString returned the empty bucket in which a new string could be interned, as findEntry does? We can avoid re-doing the probing in the call to tableSet later.

**Comment by munificent** [comment]
> Shouldn't we also compare the hash of the strings first, before memcmp? Wouldn't that speed up the interning logic?

Good idea! In this case, it's unlikely to make a big difference since we already know the string is at least in the same probe sequence as the desired hash. But it's quick and probably worth doing.

> Also, wouldn't it be better if tableFindString returned the empty bucket in which a new string could be interned, as findEntry does? 

Yeah, that would be a little faster. I didn't mostly because it would require changing more code from previous chapters, and I try to minimize that. In a real implementation, I would do what you suggest.
