### ISSUE TITLE
Provide links for all topics (13 . 4 Conclusion)

### ISSUE THREAD

**Issue by cm1776** [munificent/craftinginterpreters#388]
Some random web surfer, upon landing at http://www.craftinginterpreters.com/inheritance.html#conclusion, may not realize that all the topics listed (after "we have learned and implemented…") have actually been covered earlier in the book or in the chapter.

Please provide links to these topics to avoid confusion to such a person.

Example: "tokens and lexing" has a link, but "prefix and infix expressions" does not.

**Comment by munificent** [comment]
The ones that don't have links are because they are part of a chapter that's already linked to. I tried to find sections within the chapter to link to, but that doesn't always work, and it felt weird to me to link to the same chapter multiple times. It's not ideal, but my goal was mostly to list the topics and not so much the chapters. (The table of contents is already a list of chapters, after all.)

It's not a perfect list, but I think I'll leave it as-is.
