### ISSUE TITLE
GenerateAst adds java.util.List to generated files prematurely.

### ISSUE THREAD

**Issue by AndroxxTraxxon** [munificent/craftinginterpreters#411]
The need for the `writer.println("import java.util.List;");` is not introduced until 8.5.2, but it is written into the creation of the script at 5.2.2.

I know this is nitpicky, but it seems like it would follow in the method of introducing only what you need as you go.

**Comment by munificent** [comment]
This is a fair point, but I think it's a little simpler to just get it out in chapter 5 with all the other boilerplate rather than have to revisit it later. Since it's just in a separate utility script, I don't think it's quite as important to be incremental as it is with the code in the interpreters themselves.
