### ISSUE TITLE
Question: Section 21 . 3 Reading Variables

### ISSUE THREAD

**Issue by cm1776** [munificent/craftinginterpreters#447]
Consider the code snippet:

      case OP_GET_GLOBAL: {                                     
        ObjString* name = READ_STRING();                        
        Value value;                                            
        if (!tableGet(&vm.globals, name, &value)) {             
          runtimeError("Undefined variable '%s'.", name->chars);
          return INTERPRET_RUNTIME_ERROR;                       
        }                                                       
        push(value);                                            
        break;                                                  
      }                                                         

Question: Which of the following is better?

 runtimeError("Undefined variable '%s'.", name->chars); 
                            OR
 runtimeError("Undefined variable '%.*s'.", name->length, name->chars);

**Comment by munificent** [comment]
The latter is required. Because the lexeme points back into the original source string, it isn't actually null terminated. If we just use `%s`, it will print the lexeme... and the rest the entire program. The not-well-known `%.*s` syntax lets you specify the length formatting parameter as an actual numeric argument. We use that to only print as much of the source string as the token contains.

**Comment by cm1776** [comment]
The code snippet is from Chapter 21 and the last time I checked, it is still the same.

I guess you need to change it. 

In other words, change:
   runtimeError("Undefined variable '%s'.", name->chars);
to:
   runtimeError("Undefined variable '%.*s'.", name->length, name->chars);

**Comment by cm1776** [comment]
Thanks for your answer.

Since an ObjString contains a null terminated string, then it's okay to write:
`runtimeError("Undefined variable '%s'.", name->chars);`
