### ISSUE TITLE
Question: Chapter 18 (Location of isFalsey(Value value))

### ISSUE THREAD

**Issue by cm1776** [munificent/craftinginterpreters#452]
The 'valuesEqual(Value a, Value b)' function is defined in the value.c module. It lets us know if two Values are equal.

However, the 'isFalsey(Value value)' function, which tells us whether a Value is false-y, is defined in vm.c.  

I wonder whether there is some performance related reason for this choice?

I would have thought that since both functions tell us things about Values, they should be defined in the same module (value.c) especially as the value.c module is all about Values.

**Comment by munificent** [comment]
Uh, now that you mention it, I don't think there's a real reason. It *might* be easier for the compiler to inline the function because it's declared `static` inside "vm.c", but that wasn't a deliberate choice on my part. Logically, it should probably be in "value.c". But keeping it in "vm.c" does spare us the boilerplate of declaring it in the "value.h" header too. I think I'll leave it as it is.
