### ISSUE TITLE
Missing void in function argument declaration

### ISSUE THREAD

**Issue by binji** [munificent/craftinginterpreters#459]
I started reading [Calls and Functions](http://craftinginterpreters.com/calls-and-functions.html), and noticed that `newFunction` is defined as `ObjFunction* newFunction()`.

Since this is compiled as C (not C++), this actually makes an old-style declaration, which doesn't produce a compile-time error when called with the wrong number of arguments. See https://en.cppreference.com/w/c/language/function_declaration#Notes, and https://godbolt.org/z/9KXV9g for an example.

You can fix this by defining it as `ObjFunction* newFunction(void)` instead. I think the gcc flag `-Wstrict-prototypes` will catch it as well.

Thanks for the awesome book!

**Comment by munificent** [comment]
I learned something new with this issue! In my own C code, I'll start doing this. I'm tempting to do it for the book but [as far as I can tell, few readers are familiar with this](https://twitter.com/munificentbob/status/1156938611729715200). I don't want to distract people with an unfamiliar C idiom, even if it's a good one, because the book ultimately isn't about C. Especially given that many readers are coming from Java or JS backgrounds, I think keeping it simpler is better.

Thank you for bringing this to my attention!
