### ISSUE TITLE
Confusion about "Representing Code" chapter

### ISSUE THREAD

**Issue by Zelatrix** [munificent/craftinginterpreters#488]
I'm on the chapter about representing the code for the Java interpreter, and while I understand the code snippets in the book, I am totally confused as to why I'm receiving errors when I try to run the code. I'm being told that words like "Visitor" in the following line, and all the appearances of the word "expr" are not recognised. 

```java
public class ASTPrinter implements Expr.Visitor<String>
```

How does the IDE know about these if they're stored as strings?

**Comment by munificent** [comment]
You have to *run* the AST generator script before you can *build* the rest of jlox. The AST generator is a separate standalone Java program that outputs other Java source files to be used by jlox.

Let me know if that doesn't help and I'll reopen this. :)

**Comment by Zelatrix** [comment]
The AST generator script is what is giving me all the errors.

**Comment by munificent** [comment]
The line of code you're showing here is `ASTPrinter`, which isn't part of the AST generator. Can you show the full error output you're seeing?

**Comment by Zelatrix** [comment]
When I run the ASTGenerator script, I get a bunch of ``class, interface, or enum expected`` errors kicked out by the ASTPrinter. If I completely comment out the ASTPrinter class and run it, I get the error thrown from ASTGenerator.

**Comment by munificent** [comment]
The ASTGenerator does not use or import ASTPrinter at all. Again, can you show me the exact command you are running and the output you get? "A bunch of errors" is not specific enough for me to help you.

**Comment by virusdaemon** [comment]
Respectfully, I think all this stems from a communications issue at the point you say "Run this script now and it blasts out a few dozen lines of code". 

May I suggest you insert after that sentence, partly in bold, something like "Make sure you specify as your argv[0] the pathname of the directory containing your other Lox source files, so it can be compiled with the rest of Lox - because all later code in this chapter requires that Expr.java be correctly generated there." (I just ran into similar problems, just because I'd over-cautiously specified a test directory as output just to see what would happen, and didn't twig...)

HTH
