### ISSUE TITLE
Your Java Resolver Allow Returning from a Compiler

### ISSUE THREAD

**Issue by ChayimFriedman2** [munificent/craftinginterpreters#498]
When displaying the idea of constructors in lox (Chapter 12, "Classes", section "Constructors and Initializers"), you said you don't want to allow returning with value from compiler. So you added the following check to the Resolver:

```java
public Void visitReturnStmt(Stmt.Return stmt) {
    if (stmt.value != null) {
        if (currentFunction == FunctionType.INITIALIZER) {
            Lox.error(...);
        }
        // ...
    }
}
```

But this code has a problem. Imagine the following situation:

```lox
class C {
    init() {
        // ...
        return nil;
    }
}
```

`nil` is translated to Java's `null`, so the`if` won't be executed.

But, although you may claim this is OK, it has several problems:

- After all, it **allows** return with value from a constructor. It's confusing and seems to be a bug in the language implementation.
- Even worse, the caller code expects `nil`, but gets the class (since constructor always returns their class)!

The solution I implemented is: add a field, I named it `hasValue`, to the class `Stmt.Return` (change `AstGenerator.java`). Then, _in the parser_, set it to true only when the statement has a value. All you've left is to check in the resolver as follows:

```java
public Void visitReturnStmt(Stmt.Return stmt) {
    if (stmt.value != null) {
        // ...
    }

    if (stmt.hasValue && currentFunction == FunctionType.INITIALIZER) {
        Lox.error(...);
    }
}
```

**Comment by munificent** [comment]
I think you are confusing the runtime representation of values and the compile-time ASTs.

The resolver works with ASTs, not runtime values. A `null` value for `stmt.value` does not mean the runtime value `nil`, it means the return statement value expression is `null` instead of having an AST. That means we know there is no return value at all, and an error is shown. All of this happens before any code is run. If you run your example program in jlox, it correctly prints:

```
[line 3] Error at 'return': Cannot return a value from an initializer.
```
