### ISSUE TITLE
Grammar Nit: Section 25.0

### ISSUE THREAD

**Issue by jptemplin** [munificent/craftinginterpreters#505]
Original text:

Because some locals have very different lifetimes, we will have two implementations strategies, one optimized for each. 

Simple fix: replace: "implementations" with "implementation"

But...in general, I found this sentence a bit awkward, especially how it ends (each...what?). If I were wordsmithing this, I'd write: "Because some locals have very different lifetimes, we will need two [separately-]optimized implementation strategies." I go back and forth on whether or not to include the word "separately".

Challenging chapter. Very easy at this point to get lost in the nest of pointers.

**Comment by cm1776** [comment]
Replace: "Because some locals have very different lifetimes, we will have two implementations strategies, one optimized for each."

by

"Because some locals have very different lifetimes, we will have two implementation strategies." 

Reason: The two implementation strategies are explained in the sentences that follow the above sentence, so we do not need ", one optimized for each".

**Comment by munificent** [comment]
> Challenging chapter. Very easy at this point to get lost in the nest of pointers.

Yup. I walked through it as carefully as I could, but this is probably the most technically complex chapter in the book. (Even the next chapter on GC is simpler.) It's downhill from here!

> "Because some locals have very different lifetimes, we will have two implementation strategies."

*<chef kiss>*
