### ISSUE TITLE
Confusing Question in Chapter 14, Challenge 2

### ISSUE THREAD

**Issue by jonathanabrown** [munificent/craftinginterpreters#514]
Challenge two of chapter 14 (https://craftinginterpreters.com/chunks-of-bytecode.html#challenges) is confusing worded. Should one use multiple operands in the bytecode to represent value stored, or is `OP_CONSTANT_LONG` used for storing very large values, or for more values that we previously had? Is the constant array a new array in `Chunk` or is referring to the array we previously used for Values?

**Comment by munificent** [comment]
It's not about the size of values, but the number of unique constants in a chunk. `OP_CONSTANT_LONG` is for when a chunk has more than 255 constants and you need a larger operand to store the constant table index itself.

**Comment by Frick-David** [comment]
@amyjbrown I am working on this now, and am making some progress. I do agree that the question confused me for a bit and I looked into making a 24-bit data type [like here](https://stackoverflow.com/questions/7416699/how-to-define-24bit-data-type-in-c). However, I have a better understanding now, and wanted to point out stuff that helped me. What the question is saying is that in main the lines:
```
  Chunk chunk;
  initChunk(&chunk);

  int constant = addConstant(&chunk, 1.2);
  writeChunk(&chunk, OP_CONSTANT, 123);
  writeChunk(&chunk, constant, 123);
  writeChunk(&chunk, OP_NEGATE, 123);
  writeChunk(&chunk, OP_RETURN, 123);
...
```
The variable `chuck` can only hold 255 constants. Calling `addConstant` on it 256 would break the program (could test this with a for loop). The code we want to add in the exercise is to allow more than 255 (2 bytes worth rather than 1, I think) constants to be added by using the `OP_CONSTANT_LONG` Opcode. 
-- What I did to start off is duplicate all the OP_CONSTANT code and make a 2nd chunk in main like so:
```
  Chunk chunk2;
  initChunk(&chunk2);
  // OP_CONSTANT_LONG
  constant = addConstant(&chunk2, 2.5);
  writeChunk(&chunk2, OP_CONSTANT_LONG, 123);
  writeChunk(&chunk2, constant, 123);
  writeChunk(&chunk2, OP_RETURN, 123);
  disassembleChunk(&chunk2, "2nd Test Chunk");
  interpret(&chunk2, vm);
...
freeChunk(&chunk2);
```
If set up properly, it should display the same output as OP_CONSTANT (I would change the number being outputted -- I put 2.5).
The next step is to then get it to accept more than 255 constants, which I hope to accomplish tomorrow. Hope this helps. I am getting it slowly but surely.

**Comment by Frick-David** [comment]
@munificent Is this correct? I think I got it, but am not fully sure.

```
void writeConstant(Chunk* chunk, Value value, int line) {
  if (chunk->capacity < chunk->count + 1) {
    int oldCapacity = chunk->capacity;
    chunk->capacity = GROW_CAPACITY(oldCapacity);
    chunk->code = GROW_ARRAY(chunk->code, uint8_t,
        oldCapacity, chunk->capacity);
    chunk->lines = GROW_ARRAY(chunk->lines, int,
        oldCapacity, chunk->capacity);
  }
  writeValueArray(&chunk->constants, value);
  chunk->lines[chunk->count] = line;
  chunk->count++;
}
```

In vm.c, we read three constants, one for each byte. I then assume we want to push them all as one value.

```
      case OP_CONSTANT_LONG: {
        Value constants[3] = { READ_CONSTANT(), READ_CONSTANT(), READ_CONSTANT()};
        push(constants[0] + constants[1] + constants[2], vm);
        break;
      }
```

For debugging, I have constantLongInstruction called, it gets three bytes and prints the value of them, then moves 4 bytes past the instruction.

```
static int constantLongInstruction(const char* name, Chunk* chunk, int offset) {
  uint8_t constants[3] = {chunk->code[offset + 1], chunk->code[offset + 2],
                            chunk->code[offset + 3]};
  printf("%-16s %4d '", name, constants[0] + constants[1] + constants[2]);
  printValue(chunk->constants.values[constants[0] + constants[1] + constants[2]]);
  printf("'\n");
  // Move 4 bytes to the end of the OP_CONSTANT_LONG instruction.
  return offset + 4;
}
```

So then we only need to make main produce a correct constantLongInstruction, like so:
```
  Chunk chunk2;
  initChunk(&chunk2);
  int constant2 = addConstant(&chunk2, 1.2);
  int constant3 = addConstant(&chunk2, 1.2);
  int constant4 = addConstant(&chunk2, 1.2);
  writeChunk(&chunk2, OP_CONSTANT_LONG, 123);
  writeConstant(&chunk2, constant2, 123);
  writeConstant(&chunk2, constant3, 123);
  writeConstant(&chunk2, constant4, 123);
  writeChunk(&chunk2, OP_NEGATE, 123);
  writeChunk(&chunk2, OP_RETURN, 123);
  disassembleChunk(&chunk2, "2nd Test Chunk");
  interpret(&chunk2, vm);
```
It is a chuck that has three constants, write the instruction, then writes the constants, then goes through it. 

My output when running this is :
```
== 2nd Test Chunk ==
0000  123 OP_CONSTANT_LONG    0 '1.2'
0004    | OP_NEGATE
0005    | OP_RETURN
          
0000  123 OP_CONSTANT_LONG    0 '1.2'
          [ 3.6 ]
0004    | OP_NEGATE
          [ -3.6 ]
0005    | OP_RETURN
-3.6

```
I think I got it, but am not sure.

**Comment by danieldaeschle** [comment]
I don't understand it....
