### ISSUE TITLE
Chapter 5 Challenge 2 Example Needed

### ISSUE THREAD

**Issue by jeschkies** [munificent/craftinginterpreters#536]
Hi,

I'm writing the interpreter in Rust and have a hard time replacing the visitor pattern with a more functional approach. Pattern matching over each type in each visit function is straight forward. There is a great answer on [Stackoverflow](https://stackoverflow.com/questions/8618082/visitor-pattern-in-scala). However, it would still require modifying each visit function, eg an `AstPrinter` and `RpnPrinter`, each time a new expression type is added. Maybe I misunderstand something. Unfortunately I don't quite understand the answer either

> One way is to create a record or tuple containing a function pointer for each operation. In order to allow defining new types and passing them to existing code, these functions need to encapsulate the type entirely -- the existing code isn't aware of it, so it can't type check. You can do that by having the functions be closures that all close over the same shared object, "this", basically.

Are "new types" new expressions in this context? What would be the functions?

Maybe I'm getting the questions wrong and it's rather about how to capture some kind of objects in a pure functional language.

**Comment by munificent** [comment]
> it would still require modifying each visit function, eg an `AstPrinter` and `RpnPrinter`, each time a new expression type is added.

Yes, that's essential. Think about it like this: You have E different kinds of expressions and O different operations you can perform on them. That means you need E×O chunks of code in order to implement each operation for every kind of expression. Any time you add an expression type and increase E by 1, you need to implement another O chunks of code to support all the operations on that new type. Conversely, any time you add a new operation, you need another E chunks of code to implement that operation for all types.

In an object-oriented language using virtual methods, all of the operations for a single type are bundled together with the type. Using the visitor pattern lets you move those operations out to a separate Visitor class, one visitor for each operation. Pattern-matching directly puts all of the cases for a single operation into a single function. So there are different ways to *organize* the operations, but fundamentally you still gotta put the E×O *somewhere*.

I wrote about this at more length [here](http://journal.stuffwithstuff.com/2010/10/01/solving-the-expression-problem/).

**Comment by jeschkies** [comment]
Thanks for you help 🙂
