### ISSUE TITLE
Assignment Operator in Scanning Chapter

### ISSUE THREAD

**Issue by dbarisakkurt** [munificent/craftinginterpreters#56]
The assignment operator wasn't mentioned in the Scanning chapter. Either you should explain it in the chapter, or make it a challenge.

**Comment by munificent** [comment]
It's only referred to as `=`, but the assignment operator is implemented in [section 4.5.2](http://www.craftinginterpreters.com/scanning.html#operators). Its TokenType is `EQUALS`. :)

**Comment by dbarisakkurt** [comment]
you are right. my bad. i was expecting a token named as ASSIGNMENT instead of EQUAL so badly. I missed it.

**Comment by munificent** [comment]
I agonized over whether the names of the TokenTypes should describe what the token is *for*—assignment, multiplication, etc.—or what it is syntactically—equals, star, etc. I eventually settled on the latter because it seemed a little less ambiguous. (Consider that in, say, Java, a `<` can mean comparison or the beginning of a type argument list.)
