### ISSUE TITLE
Question: Scheduling Garbage Collection

### ISSUE THREAD

**Issue by schtauffen** [munificent/craftinginterpreters#570]
Would it be a valid approach to, instead of triggering `collectGarbage()` from within `reallocate()`, have `reallocate` set a flag on the vm and then have the vm call `collectGarbage` before or after its next run iteration ? I feel like this would reduce (eliminate?) GCs that delete transitionary data and reduce the need for the push()/pop() work arounds.

```c
  for (;;) {
    if (vm.shouldGC) {
      collectGarbage();
    }
```
_in vm run()_

Forgive me if there is a lot of prior art on this, the topic has been difficult for me to google well.

**Comment by munificent** [comment]
Yes, this is definitely feasible. Many incremental GCs that run periodically instead of on-demand do something along these lines. You're right that it means less shenanigans to make sure everything is reachable.

There are important performance trade-offs to consider, though. The main `for (;;)` loop in `run()` is the most performance critical piece of code in the whole VM. Any code that executes on every iteration can dramatically slow the VM down. Even a simple if check like this can be a major problem. It would be worth trying it to see what the actual effect is.

There is continuum between:

* The GC can run at any time, so every value needs to always be reachable by the GC.
* The GC only runs at certain known points, but you must ensure the amount of memory that can be allocated between those points is constrained somehow.

In the literature, these points where the GC is allowed to run are called "safe points". Most performance GCs use them because it makes it easier to deal with references to live objects that are only stored in registers. It also makes it easier to coordinate with other threads.

But some care must be taken that the running program reaches safe points frequently enough to avoid the GC being starved. Sort of like a videogame, you don't want to accumulate more and more and more stuff before you reach the next save point. In the context of a GC, it means you risk running out of memory.

Another option would be to not GC after *every* instruction, but only after ones that can potentially allocate. So you've check at the end of the instruction handlers for things like `OP_CALL` and `OP_ADD` (for string concatenation), but not `OP_GET_LOCAL`, etc.
