### ISSUE TITLE
30 [suggestion] Mesauring memory improvements due to NaN-boxing

### ISSUE THREAD

**Issue by belkadan** [munificent/craftinginterpreters#684]
> That’s not a huge improvement, especially compared to the profound effect of making hash table lookups faster. I added this optimization in large part because it’s a good example of a certain *kind* of performance work you may experience, and, honestly, because I think it’s technically really cool. It might not be the first thing I reached for if I were seriously trying to make clox faster. There is probably other lower-hanging fruit.

While NaN-boxing may not improve *speed* that much, I wonder how much it improves *memory usage,* since it cuts the storage for every Value in half. The memory infrastructure is already set up to measure this, with all allocations going through `reallocate`, so it should be easy enough to measure differences in peak memory usage. That could be an actual section in the text, or an extra challenge in the final chapter.

**Comment by munificent** [comment]
This would be interesting, but for me the biggest challenge is finding a useful representative benchmark. This is even harder for memory than it is for performance, especially in Lox which doesn't have lists or much in the way of useful data structures.

It's a good idea, but I'm gonna skip it mainly because I gotta get this book done. :)
