### ISSUE TITLE
Are you accepting code style suggestions/PRs?

### ISSUE THREAD

**Issue by joshiraez** [munificent/craftinginterpreters#711]
Hi,

Im loving your book so far. I have been working with Java in a focus in Clean Code for some years and I have a few suggestions. But I dont know if those are a priority for you and the code is very good already, they are just tidbits

Posting just because I dont want to post unwanted issues and add noise :(

**Comment by munificent** [comment]
In principle yes, all suggestions are welcome. I can't promise I will accept all or even most of them. :)

The code style in the book is deliberately not "good" Java style. My intent is to make the code as simple and easy to read as possible. It's not to build a large, easy-to-maintain codebase. So things like proper access control and other good engineering practices are deliberately omitted because they make the code more verbose for no benefit to the book.

But, yes, I'd like to hear your suggestions!
