### ISSUE TITLE
Minor issue with section 9.3

### ISSUE THREAD

**Issue by tallforasmurf** [munificent/craftinginterpreters#717]
In 9.3, there are occasions where "and" and "or" are used as to qualify "expression" but are in roman type:

* For an and expression to evaluate to something truthy,...
* The code to parse a series of or expressions 
* the new and expression:

I would suggest these should be `and` and `or` to avoid ambiguity.

Edit: similar issues later with "while loop" and "for loop". Thinking about this, in all cases the Lox keyword is being used to modify a noun, so a different way to handle it would be with hyphens to make compound nouns: "and-expression", "or-expression", "for-loop", "while-loop". This eliminates syntactic ambiguity (e.g. between "Lox needs for loops" which might be multiple requirements to have loops) without requiring a lot of font switching.

**Comment by munificent** [comment]
Yes, I think you're right. I've been on the fence about whether to use code font in prose for all statement and expression types that have a keyword in their name. I hesitated because it was pretty visually distracting, but it does make for some confusing text like you note. I ended up changing all expressions and statement types to use code font, and then tweaked the CSS to make it less distinct.
