### ISSUE TITLE
How to add array to clox?

### ISSUE THREAD

**Issue by Livinglist** [munificent/craftinginterpreters#745]
I cannot figure it out..

**Comment by mcfriend99** [comment]
It?s actually our straightforward. I think Bob has covered the important ground. I was able to successfully add lists, tuples and maps/dictionaries  as well anonymous functions and other higher ended stuffs pretty easy based on what I learned from Bob.You can use linked lists or Value* to easily do it.Let me know if you want me to share my implementation.On Tue, 26 May 2020 at 19:33, Jiaqi Feng <notifications@github.com> wrote:
I cannot figure it out..

?You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Livinglist** [comment]
> It’s actually our straightforward. I think Bob has covered the important ground.  I was able to successfully add lists, tuples and maps/dictionaries  as well anonymous functions and other higher ended stuffs pretty easy based on what I learned from Bob. You can use linked lists or Value* to easily do it.Let me know if you want me to share my implementation.

Yes please! I would love to see your implementation!

**Comment by munificent** [comment]
Also see here: https://github.com/munificent/craftinginterpreters/blob/master/note/answers/chapter13_inheritance/3.md

**Comment by mcfriend99** [comment]
Like Bob said, it's pretty easy and wouldn't be teaching any new concepts. I was able to add arrays, dictionaries as well as generics in my own implementation without any real struggle. By the way @munificent this is the book of our time on this topic. 👍
