### ISSUE TITLE
Section 23.2: [question] Associativity for the AND operator

### ISSUE THREAD

**Issue by katjonathan** [munificent/craftinginterpreters#768]
The AND operator is implemented as so:
```c++
static void and_(bool canAssign) {
  int endJump = emitJump(OP_JUMP_IF_FALSE);

  emitByte(OP_POP);
  parsePrecedence(PREC_AND);   //  <- right-associative?

  patchJump(endJump);
}
```
 However, wouldn't it make more sense for the AND operator to be left-associative instead of right-associative? I'd think the problematic line would be changed to `parsePrecedence(PREC_AND+1)`. Why is it right-associative instead of left?

**Comment by munificent** [comment]
It is left associative, it just looks funny. :)

Note that the compiler emits the jump instructions *before* compiling the right operand. Usually, when compiling a binary operator, you compile the two operands first and then emit the instruction for the operator. It's a post-order traversal. Because of that, if you recurse at the same precedence level for the RHS, you end up not executing the leftmost operator until all of the RHS is done.

But for `and` and `or`, we need to short-circuit. To handle that, the compiler does an in-order traversal—it emits code for the first `and` before recursing into and compiling the RHS. The only thing is does at the very end is patch the jump so that if the first `and` fails, then it jumps over the entire RHS, regardless of how many subexpressions there are.

**Comment by katjonathan** [comment]
@munificent: Is there any way to compiler `and` and `or` clauses without jumping? (Like similar to how we did things for other types of expressions?) I initially though that if we somehow push the operands _backwards_ onto the VM stack, then we can just take a look at the first opera down and decide whether to skip the rest from there. Unfortunately, that approach doesn’t seem to be viable for single-pass compilation.

**Comment by munificent** [comment]
> @munificent: Is there any way to compiler `and` and `or` clauses without jumping? (Like similar to how we did things for other types of expressions?)

No, you need some sort of just to ensure that the right operand is short-circuited when necessary. Since the RHS can execute code with arbitrary user-visible side effects, you need to avoid evaluating its code *at all* if the LHS value results in something that trigger short-circuiting.
