### ISSUE TITLE
Question about OP_CLOSURE

### ISSUE THREAD

**Issue by akva** [munificent/craftinginterpreters#775]
I have a question about `OP_CLOSURE` opcode. `OP_CLOSURE` has this odd encoding with variable number of arguments and therefore the function object stores `upvalueCount` so that vm would know how many arguments to read. The information about upvalues themselves is stored in`Compiler.upvalues` though, and emitted into the bytecode.

```
emitBytes(OP_CLOSURE, makeConstant(OBJ_VAL(function)));

for (int i = 0; i < function->upvalueCount; i++) {
    emitByte(compiler.upvalues[i].isLocal ? 1 : 0);
    emitByte(compiler.upvalues[i].index);
}
```

I am wondering if it's possible to store `upvalues` in the function object as well (next to `upvalueCount`)? This way `OP_CLOSURE` does not need any arguments other than function constant. It seems this would eliminate some complexity. Am I missing something?

Thank you!

**Comment by munificent** [comment]
If the upvalues were stored directly in ObjFunction, then there would be no need for ObjClosure at all. But we need ObjClosure because different executions of the same function declaration can close over different values:

```
fun capture(n) {
  fun closure() {
    print n;
  }
  return closure;
}

var a = capture("a");
var b = capture("b");
a();
b();
```

Here, there is only one ObjFunction for `closure()`, but there are two ObjClosures for it. Each one has a different upvalue array that captures different variables.

**Comment by akva** [comment]
Sorry, maybe I wasn't clear enough. I didn't mean the runtime upvalues (`ObjUpvalue`), obviously those would still be stored in `ObjClosure`. Rather, I am talking about the compile-time meta data about upvalues

```
typedef struct {
  uint8_t index;
  bool isLocal;
} Upvalue;
```

I think these could be stored in `ObjFunction` instead of in `Compiler`. Then the code in vm.c becomes something like this:

```
case OP_CLOSURE: {
        ObjFunction* function = AS_FUNCTION(READ_CONSTANT());
        ObjClosure* closure = newClosure(function);
        push(OBJ_VAL(closure));
//> interpret-capture-upvalues
        for (int i = 0; i < closure->upvalueCount; i++) {
          uint8_t isLocal = function->upvalues[i].isLocal; // READ_BYTE();
          uint8_t index = function->upvalues[i].index; // READ_BYTE();
          if (isLocal) {
            closure->upvalues[i] = captureUpvalue(frame->slots + index);
          } else {
            closure->upvalues[i] = frame->closure->upvalues[index];
          }
        }
//< interpret-capture-upvalues
        break;
      }
```

**Comment by munificent** [comment]
Ah, yes. Yes, we could do that. :)

It's sort of a six of one, half dozen of the other sort of thing. The compiler needs to shunt a little information over to the runtime about the layout of the function's upvalues. We could store that in the function, or we could store it inline directly in the bytecode for function declaration. I went with the latter, for no particularly strong reason. Maybe because it's how Lua does it?

**Comment by akva** [comment]
Thank you for clarifying this. I was just worried, as I was reading the book, that I was missing some obvious reason why that has to be stored inline in the bytecode. Maybe I was confused because upvalueCount _is not_ inlined in the bytecode.
