### ISSUE TITLE
Chapter 26: Potential GC bug in tableSet()

### ISSUE THREAD

**Issue by katjonathan** [munificent/craftinginterpreters#792]
When in `tableSet()`, there may be a `reallocate()` call via `adjustCapacity()`. In the case where this happens, the key and value which are passed as parameters are not marked as roots and will be swept away by the garbage collector before they can be added to the table.

**Comment by BigZaphod** [comment]
I just ran into this myself. I think the main problem is caused by `allocateStringObject()`. It created a new object just before trying to put it into the interned string table but the new object only exists on the C stack at that point. If `tableSet()` triggers a GC it'll end up freeing that brand new object before it ever made it into the table. So far this is the only place I've run into this problem so I'm inclined to think either I missed something when I was manually typing it out or this is a bug in the book.

The fix seems easy enough to me - just push the new object on to the VM's stack before calling `tableSet()` and then pop it after.

**Comment by BigZaphod** [comment]
I think I spoke too soon - it looks like `writeValueArray()` has the same problem. I ran into this one by way of `addConstant()` in the compiler. Perhaps the better solution is to add `push`s and `pop`s to both `tableSet()` and `writeValueArray()` just to be safest.

**Comment by BigZaphod** [comment]
lol I just saw in the section "Garbage Collection Bugs" that both of the things I ran into are there - only the fix is different. Rather than changing `tableSet()` and `writeValueArray()` he just fixed up `addConstant()` and `allocateString()`. I suppose both are valid fixes although it feels safer to me to just do it in the table and array - and only when they decide to they're going to need to resize.

**Comment by munificent** [comment]
> When in `tableSet()`, there may be a `reallocate()` call via `adjustCapacity()`. In the case where this happens, the key and value which are passed as parameters are not marked as roots and will be swept away by the garbage collector before they can be added to the table.

That's true. There are a couple of GC bugs deliberately left in early on in the book. As far as I know, they all get fixed when we reach: http://craftinginterpreters.com/garbage-collection.html#garbage-collection-bugs

**Comment by dallonf** [comment]
I just ran into this myself; at the start of 26.6, it implies that you can run the code now and see it work with the stress testing flag on. But because of the stress testing flag, it segfaults as soon as it tries to initialize the native `clock`, because it allocates the string`"clock"`, but has to grow the table before adding it to the global strings table, and so collects the string before it has a chance to be added to the stack.

I spent a good amount of time troubleshooting before it occurred to me it may be a bug in the book's code and not a typo on my part! As a sidenote, is there a list of errata somewhere for this book that I can check if there's anything I need to do differently than my physical copy in general?
