### ISSUE TITLE
Garbage Collection [question]: Marking the constant table

### ISSUE THREAD

**Issue by katjonathan** [munificent/craftinginterpreters#795]
In `blackenObject()` how come we mark the *entire* constant table? Wouldn’t that mean that no constants would ever be collected? If we had a code segment like:
```
var string = “a”;
string = “b”;
string = “c”;
```
Then the strings `”a”` and `”b”` are never collected. A garbage collector that never collects defeats the very purpose of a garbage collector!

**Comment by BigZaphod** [comment]
The constants being marked in the `blackenObject` step are the constants _inside_ of a function object, so they're things that _that particular function object_ require - not every global constant in the program. If the GC gets into `blackenObject` for a function, it means it's already been marked as accessible from a root and therefore is in use so the `blackenObject` step is now just going a step farther to make sure anything the function object itself needs doesn't disappear either (which would be bad).

The GC *does* mark the entire global table which means no globals will ever get collected - but that makes sense because your program likely assumes the globals will exist and be there when it wants them.

In your example program, the "a" and the "b" would both be collected if you're in the global scope. However if that was a function body like this then its a different story:

````
fun testing() {
  var string = "a";
  string = "b";
  string = "c";
}
````

In this case all 3 strings would be constants this function needs at runtime so they would stick around in `testing`'s constant table for as long as the `testing` function exists. Since global functions are just function objects assigned to a name, redefining `testing` to be something else later would replace it and therefore the old function object - along with its constant table - could then get collected.

I hope this makes some sense. (And I hope it is all correct!)

**Comment by munificent** [comment]
> The constants being marked in the `blackenObject` step are the constants _inside_ of a function object, so they're things that _that particular function object_ require - not every global constant in the program.

You're exactly right. :)
