### ISSUE TITLE
Should the comment parsing handler do the end-check before peeking in the `while` loop?

### ISSUE THREAD

**Issue by nikki93** [munificent/craftinginterpreters#809]
https://github.com/munificent/craftinginterpreters/blob/499dee396d679217583e5d05b64582e31872efce/c/scanner.c#L109

Over here, would it better to have this be the other way round (i.e., `!isAtEnd() && peek() != '\n'`) instead? It seems fine as-is because at the end you're still in valid memory and on a `'\0'` character, but it depends on that detail of `isAtEnd()`. I'm working through the book in C++ and in my implementation the source is an `std::string_view` and `isAtEnd()` is implemented as `return current == source.end()`--where I think the order as-given would exhibit undefined behavior by accessing out-of-bounds in `peek()` at the end of the source.

**Comment by munificent** [comment]
Good question! In C, doing the `peek()` first is safe because, as you note we never go past the null terminator, so there is always a valid character we can look at.

When you port it to C++, you may need to change this if you aren't using C-style null terminated strings. You could reverse the order like you suggest, or you could have your `peek()` function check to see if you're at the end and return some kind of sentinel value in that case.

**Comment by nikki93** [comment]
Makes sense, thanks, and also thanks for the great book! :)
