### ISSUE TITLE
No color coding: Section 21.1.1

### ISSUE THREAD

**Issue by cm1776** [munificent/craftinginterpreters#811]
The code that appears after "While we’re in the interpreter loop, we should delete a bit of code:" is NOT color coded.

![screenshot-craftinginterpreters com-2020 09 05-08_48_27](https://user-images.githubusercontent.com/44275568/92300721-f8484a80-ef54-11ea-9bec-234a42c87adf.png)

**Comment by munificent** [comment]
It is, actually. It just doesn't look like it. In this snippet, there is a line of context before and after the snippet which are grayed out like context lines always are. And the only line of code we add is a comment, so it's gray too.

This is the only place in the book where we remove some old code without really having any new code to replace it with. So I put that comment in there so that there is something to show in the snippet, but it ends up looking a little funny.
