### ISSUE TITLE
Ok to strip content and provide as a blog/book tool?

### ISSUE THREAD

**Issue by filiph** [munificent/craftinginterpreters#841]
Hey Bob,

First of all, congrats on the book. It looks fantastic and reads even better.

I was looking for a good way to publish articles on the web for some time now. First of all, I forbade myself to build my own solution. I'm also steering away from cool new microblog platforms. I was looking at things like https://github.com/bewuethr/pandoc-bash-blog, but that's still a lot of work, for so-so results. In the interim, I use good old WordPress, and at first I thought it'll be fine, but the slowness and inflexibility is killing me. ([See for yourself.](https://selfimproving.dev/))

Then I remembered you basically have the solution I'm looking for. I've played with the tooling this evening and I think it's just the ticket.

Here's my plan:

* Take your project
* Rip out all the content, all the images, all the styling, all the samples, all the tests, and only leave the (MIT-licensed) tooling
* Create .html (mustache) and .sass files until `dart tool/bin/build.dart` finishes successfully
* Publish the resulting scaffold + tooling on github in full MIT license (something like `craftinginterpreters-tooling`?)

Would you be okay with this? I would be the first person to take that project and build my own blog on top of it.

**Comment by munificent** [comment]
I think you'll find that tearing out all of the "Crafting Interpreters"-specific code, contentn, and styles really doesn't leave too much behind. It's mostly just a tiny HTTP server and a thin wrapper around the markdown and mustache_template packages. All of the stuff for weaving the code snippets into the Markdown is *really* specific to the book, and would be hard to separate it. Even if you could, it's probably overkill for something like a blog.

But, having said that, you're welcome to take from it what you like. I'd suggest changing the name to not mention Crafting Interpreters at all since what you'll have left isn't really related to it.

It might be a better exercise to just try building a little static site generator from scratch in Dart. I've wanted to for a long time but never found the time (aside from this very specific bespoke one). Given the watcher, markdown, mustache_template, and http packages, I don't think it would be much work and the performance is stellar. (When I rewrote the book's build system from Python to Dart, it got 10x faster and can generate the entire 200k word book in < 1s.)

**Comment by filiph** [comment]
I think you're underestimating the amount of work and experience you've put into the thin wrapper. :)

I went ahead and ported _The Self-Improving Developer_ to your system. [Here's the commit](https://github.com/filiph/selfimproving-dev/commit/183b781669ab4fa59368641742a374113e84ab85) that removed all CC content, if you want to review it. And [here's a branch](https://github.com/filiph/selfimproving-dev/tree/just-tooling) (`just-tooling`) that includes just the tooling, for people who want to do something similar to what I just did. 

Huge thanks for the system, and the books!
