### ISSUE TITLE
Missing code snippet for forward declaration of `identifierConstant` in chapter "Global Variables" (?)

### ISSUE THREAD

**Issue by jacob-church** [munificent/craftinginterpreters#849]

**Comment by cm1776** [comment]
Hello @jacob-church 

The snippet for identifierConstant(), like virtually all such snippets, has information on where the snippet should be placed. See the image below.
Depending on the relative location of a function definition, a forward declaration may not be necessary.

![image](https://user-images.githubusercontent.com/44275568/98472370-ebfd9980-21f2-11eb-9b23-8cbb6f53709d.png)

Cheers

**Comment by munificent** [comment]
@cm1776 is right. If you place the definition above `parseVariable()` like the context blurb says, you shouldn't need a forward declaration.

**Comment by mblayman** [comment]
The book is right (😁), but I experienced the same issue that jacob-church did and was stuck with a compiler error right before section "21.4 Assignment" for a little while. My error was:

```
compiler.c:216:17: error: implicit declaration of function 'identifierConstant' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
```

As breadcrumbs for other readers who might end up in the same spot, what I ultimately observed is that I accidentally put `parseVariable` after the _implementation_ of `parsePrecedence`. `identifierConstant` and `defineVariable` are set relative to the location of `parseVariable`. All three were after `parsePrecedence` instead of before `binary`.

My confusion was failing to notice that `parseVariable` was supposed to go after the *forward declaration* and not the *implementation*. This is what led to `identifierConstant` showing up as undeclared by that point in the chapter for me.

Thanks for the awesome book!
