### ISSUE TITLE
Section 21.1.1 Instruction might need to be clearer

### ISSUE THREAD

**Issue by VahnRPG** [munificent/craftinginterpreters#877]
The code block just after the line "While we’re in the interpreter loop, we should delete a bit of code." might need to be reworked some. The sidebar says "replace 2 lines" and the lack of formatting, just a comment that ends up roughly the same color as the surrounding text, led me to believe that entire block should be deleted for some reason.

In hindsight I realized what led to my mistake, but I just spent the last 2 hours trying to figure out why the vm was going crazy and never ending. I read that 'replace 2 lines', saw that what was in there was practically the same as the added ```case OP_PRINT```, and for some reason deleted the entire ```case OP_RETURN``` block from my vm.c including the eventual ```return INTERPRET_OK``` which led to the never ending code barf.

I'm not sure what to suggest for a solution. I've had similar issues with the "replace X lines" instructions, just before they hadn't been _as_ vague due to generally having code added, not just a single comment. Possibly strike throughs & a different background color for the code to be removed on top of the code to be added/replacing what's there?

**Comment by munificent** [comment]
I'm sorry you got tripped up! That is one of the trickiest snippets in the whole book. In every other place, when some existing code is removed, there is new interesting code to replace it with. But here, and only here, it's really just deleting code. I have the snippet add a comment just because otherwise it's not clear what the change is at all.

I tried a bunch of stuff to make it visually clearer what lines of code get deleted, but in everything I considered, it just made the resulting code look even more cluttered and confusing. :-/
