### ISSUE TITLE
Sections 28.5 & 30.3.3: Missing grey lines

### ISSUE THREAD

**Issue by ElessarDunadan** [munificent/craftinginterpreters#878]
These side notes are missing a thin grey line above them:
Section 28.5: "Recognizing that a few specific bytecode instructions..."
30.3.3: "Spec authors don’t like type punning..."
30.3.3: "On the off chance you find yourself..."

**Comment by munificent** [comment]
The lines are there, but not where you expect. In most cases, there is a line at the top of the aside because the first line of the aside is aligned with the text that it refers to. But in a couple of places, there is something else in the sidebar getting in the way of an aside—usually location information for a snippet. In some of those cases, the aside is instead aligned so that the *bottom* of the aside is next to the text it refers to. In those cases, the gray line is on the bottom.
