### ISSUE TITLE
Section 29.3.2: Illustration inconsistency

### ISSUE THREAD

**Issue by ElessarDunadan** [munificent/craftinginterpreters#879]
The illustration in 29.3.2 has a large section of whitespace on the right side of the image, so when the page is viewed in a single-column format, the illustration shrinks more than necessary in order to fit the whole image on the page.

**Comment by munificent** [comment]
Yeah, that is kind of annoying. There are a few illustrations like this. I pad them sometimes so that in the normal full-size view, the illustrations are all at the same scale. But this does mean that some of them get unnecessarily small when viewed on a really small screen. I think I'm just going to accept them as they are.
