### ISSUE TITLE
Typo in section 3.4.3?

### ISSUE THREAD

**Issue by 80at8** [munificent/craftinginterpreters#883]
In http://craftinginterpreters.com/the-lox-language.html) section 3.4.3

```
The other two logical operators really are control flow constructs in the guise of expressions.
An and expression determines if two values are both true. It returns the left operand if it’s false, 
or the right operand otherwise:

true and false; // false.
true and true;  // true.
```

-- The part that says it returns the left operand if it is false, or the right operand otherwise. In the example true and false it's returning false (as it should) but true is the left operand no the right one? It should be false and true; // false?

Also email contact info at the bottom of page -- bob@craftinginterpreters.com seems to bounce back with this error from O365 -- 

bob wasn't found at craftinginterpreters.com, or the mailbox is unavailable.

**Comment by cm1776** [comment]
Hello @80at8, 

The sentence you refer to ` It returns the left operand if it’s false, or the right operand otherwise:` means the following:

The `and `expression returns the left operand if the left operand evaluates to `false`; otherwise (i.e. if the left operand evaluates to `true`), the expression returns the right operand.

So the examples Bob gave are correct.

Cheers

**Comment by munificent** [comment]
As @cm1776 says, the examples there are correct. I could also show the example you have too, but doing the whole truth table felt like overkill to me.

> Also email contact info at the bottom of page -- [bob@craftinginterpreters.com](mailto:bob@craftinginterpreters.com) seems to bounce back with this error from O365 --
> 
> bob wasn't found at craftinginterpreters.com, or the mailbox is unavailable.

Oops! My email was in a weird state. It should be in a better place now.
