### ISSUE TITLE
Increasing the locals and up values limit up to UINT16_MAX + 1

### ISSUE THREAD

**Issue by mcfriend99** [munificent/craftinginterpreters#886]
Hi @munificent, 

I am trying to raise the `Local`s and `UpValue`s limit to `UINT16_MAX + 1`. 

I have tried:

- Dynamic allocation of both using init, free and write methods for both upvalues and locals,
- allocating `UINT16_MAX + 1` to `Local*` and `UpValue*` in the initCompiler method using both `malloc` and `calloc`,
- I also tried using `locals[UINT16_COUNT]` and `upvalues[UINT16_COUNT]`

Every approach gives the same problem. THEY CAN'T RUN CLOSURES. 

Closures always throw a `SEGMENTATION_ERROR` and running them though the `lldb` shows that they all exit during `markCompilerRoots`'s call to `markObject`.

Please what is the best approach to achieve a `UINT16_MAX + 1` like Java or `undefined` (technically 2^32) like python limit for locals and upvalues (I don't believe either has a concept of upvalues).

Do you have a sample code you can share??

Regards.

**Comment by munificent** [comment]
I don't have code for this lying around, but it should be possible to make it work. Things you will need to keep in mind:

1. Make sure to explicitly initialize the array pointer to `NULL`.
2. When the garbage collector marks the arrays (both in the compiler and in ObjClosure), make sure to check to see if that array is `NULL`. Also make sure to walk those arrays and mark all of their entries. Don't mark unused slots in the array since they may have stale pointers to freed objects.
3. Don't forget to free the arrays when you're done with them.

It's really useful if you haven't already to learn to step through code in a debugger so you can see exactly where it is crashing and what is in memory when that happens. llbd is fine, though I personally prefer IDE debuggers like XCode. You can solve this, but it may take some work to iron out all the bugs. Dealing with garbage collectors and dynamic memory management is tricky for all us. I ran into many many bugs and crashes when I was writing this. :)
