### ISSUE TITLE
Using resizeArray instead of ALLOCATE when resizing the array in the hashmap

### ISSUE THREAD

**Issue by nocturn9x** [munificent/craftinginterpreters#887]
Hi Bob! I haven't been opening issues here for a while, but after re-reading the chapter about hash tables (marvelous book once again, reading it is a breeze!) and after implementing my own arraylist-- following your book as well-- I noticed something weird in `adjustCapacity`. There you `ALLOCATE` an entirely new array with the new capacity and then copy the entries manually while (if I recall correctly) to do the same operation on the arraylist you used `resizeArray` (hence the allocator takes care of extending the pointer's size or copying everything over to another location and freeing the old pointer). Is there any reason for this? I tested in my implementation and it works just fine, so maybe there are some caveats that I did not consider?

**Comment by munificent** [comment]
> Is there any reason for this?

Yes, we have to re-insert all of the hash table entries one at a time because they may end up in different locations now that the array is larger. From the book:

> Back when we were doing a dynamic array, we could just use realloc() and let the C standard library copy everything over. That doesn’t work for a hash table. Remember that to choose the bucket for each entry, we take its hash key *modulo the array size.* That means that when the array size changes, entries may end up in different buckets.
>
> We need to recalculate the buckets for each of the existing entries in the hash table. That in turn could cause new collisions which we need to resolve. So the simplest way to handle that is to rebuild the table from scratch by re-inserting every entry into the new empty array.

It's possible in your tests to get lucky and either never resize the array, or coincidentally only have entries that end up in the same slot when their hash code has a new larger modulus, but if you test enough different cases, you should be able to get into a situation where an entry ends up in the wrong slot and can't be found.

**Comment by nocturn9x** [comment]
You're right. Further testing revealed the issue and I reverted back to allocate, thanks!
