### ISSUE TITLE
Token are used inside the runtime API

### ISSUE THREAD

**Issue by forax** [munificent/craftinginterpreters#93]
There are several places in the runtime part of jlox where Token object are send as argument as a compound of a name and a location, the location being used to report error at the right line.

I think it's better to let Token be token for the Scanner, i.e. an exchange object between the scanner and the parser and in the AST and in the runtime to use String and Location as two separated objects.

**Comment by munificent** [comment]
It does feel a little odd to push tokens all the way through to the runtime. But for a tree-walking interpreter as simple as jlox, I think it's reasonable. There's an equal argument that we shouldn't use ASTs in the runtime since they are the parser's responsibility, but we are obviously doing that too. :) Given that, I think it's OK to also hang tokens off those ASTs and use them too.

Passing the lexeme and location as separate parameters doesn't feel like it buys us much, and it does make the code a little more verbose. In a real implementation, that's less of a concern, but for a book, brevity matters more. (I try to keep everything within around 60 columns and I try avoid any given snippet being too many lines, so every bit counts.)

Also, there isn't currently a class to represent a location. I think passing line number as a bare integer would be a little harder to read, and yet I also don't want to spend the time introducing a mostly not-interesting Location class either.

It's a trade-off. The book is already on its way towards being pretty big, so I try to simplify where I can. 🤷‍♂️
