### ISSUE TITLE
Why use classCompiler in the code? Section 29.2

### ISSUE THREAD

**Issue by cm1776** [munificent/craftinginterpreters#941]
The variable `currentClass ` tracks the class declaration currently being compiled.

In the`classDeclaration()`function, a`classCompiler`variable is initialized and its address is assigned to the`currentClass `variable.  Several lines of code later, we come across the following:

`classCompiler.hasSuperclass = true;` and 
`  if (classCompiler.hasSuperclass) {
    endScope();
  }`

Is there a specific reason for using`classCompiler `in the 2 lines of code above rather than the`currentClass `variable? 
I expected the use of the later i.e.

`currentClass.hasSuperclass = true;` and 
`	if (currentClass.hasSuperclass) {
		endScope()
	}`

Granted, in this particular case, the results seem to be the same.

**Comment by ceronman** [comment]
In the context of the `classDeclaration()` function, `classCompiler` and `currentClass` are the same thing (currentClass is just a pointer to `classCompiler`:

```c
ClassCompiler classCompiler;
classCompiler.name = parser.previous;
classCompiler.enclosing = currentClass;
currentClass = &classCompiler;
```
So it's fine to use both, but my guess is that classCompiler is used because it's one less indirection, which might bring a tiny performance improvement. Although probably the compiler is smart enough to not make any difference.

**Comment by munificent** [comment]
No real reason that I recall. Some choices are just arbitrary. :)
